/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Analytics {
  'totalSOSReports' : bigint,
  'averageDelayPrediction' : number,
  'averageRating' : number,
  'totalFeedback' : bigint,
  'totalUsers' : bigint,
  'openSOSReports' : bigint,
  'totalIncidents' : bigint,
  'resolvedSOSReports' : bigint,
}
export interface CommuteAlert {
  'departureTime' : string,
  'userId' : Principal,
  'daysOfWeek' : Array<bigint>,
  'sourceStation' : string,
  'destinationStation' : string,
}
export interface DelayPrediction {
  'peakHour' : boolean,
  'temperature' : number,
  'userId' : Principal,
  'dayOfWeek' : bigint,
  'line' : string,
  'explanation' : string,
  'predictedDelayMinutes' : number,
  'trainType' : string,
  'distance' : number,
  'timestamp' : bigint,
  'confidence' : number,
  'rainfall' : number,
  'timeOfDay' : bigint,
}
export interface Incident {
  'latitude' : number,
  'userId' : Principal,
  'description' : string,
  'longitude' : number,
  'timestamp' : bigint,
  'stationName' : string,
  'incidentType' : string,
}
export interface Journey {
  'destination' : string,
  'source' : string,
  'userId' : Principal,
  'actualDelay' : number,
  'trainType' : string,
  'timestamp' : bigint,
  'predictedDelay' : number,
  'scheduledDeparture' : string,
}
export interface NetworkStatus {
  'status' : string,
  'timestamp' : bigint,
  'reason' : string,
}
export interface SOSReport {
  'latitude' : number,
  'resolved' : boolean,
  'userId' : Principal,
  'longitude' : number,
  'message' : string,
  'response' : [] | [string],
  'timestamp' : bigint,
}
export interface TPSIScore {
  'trend' : string,
  'line' : string,
  'score' : bigint,
  'timestamp' : bigint,
}
export interface Train {
  'eta' : string,
  'destination' : string,
  'trainNumber' : bigint,
  'trainType' : string,
  'platform' : bigint,
  'delay' : number,
}
export interface UserProfile { 'username' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeatherData {
  'temperature' : number,
  'humidity' : number,
  'timestamp' : bigint,
  'rainfall' : number,
  'condition' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCommuteAlert' : ActorMethod<[bigint], undefined>,
  'deleteIncident' : ActorMethod<[bigint], undefined>,
  'deleteSOS' : ActorMethod<[bigint], undefined>,
  'getAllTrains' : ActorMethod<[], Array<Train>>,
  'getAnalyticsSummary' : ActorMethod<[], Analytics>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommuteAlert' : ActorMethod<[bigint], CommuteAlert>,
  'getFeedbackStats' : ActorMethod<
    [],
    { 'count' : bigint, 'averageRating' : number }
  >,
  'getIncident' : ActorMethod<[bigint], Incident>,
  'getMyDelayPredictions' : ActorMethod<[], Array<DelayPrediction>>,
  'getMyJourneyHistory' : ActorMethod<[], Array<Journey>>,
  'getMySOSReports' : ActorMethod<[], Array<SOSReport>>,
  'getNetworkStatus' : ActorMethod<[], [] | [NetworkStatus]>,
  'getRecentIncidents' : ActorMethod<[], Array<Incident>>,
  'getTPSIScore' : ActorMethod<[string], [] | [TPSIScore]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeatherCache' : ActorMethod<[], [] | [WeatherData]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'resolveSOS' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCommuteAlert' : ActorMethod<
    [string, string, string, Array<bigint>],
    bigint
  >,
  'saveJourney' : ActorMethod<
    [string, string, string, string, number, number],
    bigint
  >,
  'storeDelayPrediction' : ActorMethod<
    [
      {
        'peakHour' : boolean,
        'temperature' : number,
        'dayOfWeek' : bigint,
        'line' : string,
        'explanation' : string,
        'predictedDelayMinutes' : number,
        'trainType' : string,
        'distance' : number,
        'confidence' : number,
        'rainfall' : number,
        'timeOfDay' : bigint,
      },
    ],
    bigint
  >,
  'submitFeedback' : ActorMethod<[bigint, string], bigint>,
  'submitIncident' : ActorMethod<
    [string, string, string, number, number],
    bigint
  >,
  'submitSOS' : ActorMethod<[string, number, number], bigint>,
  'updateNetworkStatus' : ActorMethod<[string, string], undefined>,
  'updateTPSIScore' : ActorMethod<[string, bigint, string], undefined>,
  'updateWeatherCache' : ActorMethod<[WeatherData], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];