/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Train = IDL.Record({
  'eta' : IDL.Text,
  'destination' : IDL.Text,
  'trainNumber' : IDL.Nat,
  'trainType' : IDL.Text,
  'platform' : IDL.Nat,
  'delay' : IDL.Float64,
});
export const Analytics = IDL.Record({
  'totalSOSReports' : IDL.Nat,
  'averageDelayPrediction' : IDL.Float64,
  'averageRating' : IDL.Float64,
  'totalFeedback' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'openSOSReports' : IDL.Nat,
  'totalIncidents' : IDL.Nat,
  'resolvedSOSReports' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'email' : IDL.Text,
});
export const CommuteAlert = IDL.Record({
  'departureTime' : IDL.Text,
  'userId' : IDL.Principal,
  'daysOfWeek' : IDL.Vec(IDL.Nat),
  'sourceStation' : IDL.Text,
  'destinationStation' : IDL.Text,
});
export const Incident = IDL.Record({
  'latitude' : IDL.Float64,
  'userId' : IDL.Principal,
  'description' : IDL.Text,
  'longitude' : IDL.Float64,
  'timestamp' : IDL.Int,
  'stationName' : IDL.Text,
  'incidentType' : IDL.Text,
});
export const DelayPrediction = IDL.Record({
  'peakHour' : IDL.Bool,
  'temperature' : IDL.Float64,
  'userId' : IDL.Principal,
  'dayOfWeek' : IDL.Nat,
  'line' : IDL.Text,
  'explanation' : IDL.Text,
  'predictedDelayMinutes' : IDL.Float64,
  'trainType' : IDL.Text,
  'distance' : IDL.Float64,
  'timestamp' : IDL.Int,
  'confidence' : IDL.Float64,
  'rainfall' : IDL.Float64,
  'timeOfDay' : IDL.Nat,
});
export const Journey = IDL.Record({
  'destination' : IDL.Text,
  'source' : IDL.Text,
  'userId' : IDL.Principal,
  'actualDelay' : IDL.Float64,
  'trainType' : IDL.Text,
  'timestamp' : IDL.Int,
  'predictedDelay' : IDL.Float64,
  'scheduledDeparture' : IDL.Text,
});
export const SOSReport = IDL.Record({
  'latitude' : IDL.Float64,
  'resolved' : IDL.Bool,
  'userId' : IDL.Principal,
  'longitude' : IDL.Float64,
  'message' : IDL.Text,
  'response' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
});
export const NetworkStatus = IDL.Record({
  'status' : IDL.Text,
  'timestamp' : IDL.Int,
  'reason' : IDL.Text,
});
export const TPSIScore = IDL.Record({
  'trend' : IDL.Text,
  'line' : IDL.Text,
  'score' : IDL.Nat,
  'timestamp' : IDL.Int,
});
export const WeatherData = IDL.Record({
  'temperature' : IDL.Float64,
  'humidity' : IDL.Float64,
  'timestamp' : IDL.Int,
  'rainfall' : IDL.Float64,
  'condition' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCommuteAlert' : IDL.Func([IDL.Nat], [], []),
  'deleteIncident' : IDL.Func([IDL.Nat], [], []),
  'deleteSOS' : IDL.Func([IDL.Nat], [], []),
  'getAllTrains' : IDL.Func([], [IDL.Vec(Train)], ['query']),
  'getAnalyticsSummary' : IDL.Func([], [Analytics], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommuteAlert' : IDL.Func([IDL.Nat], [CommuteAlert], ['query']),
  'getFeedbackStats' : IDL.Func(
      [],
      [IDL.Record({ 'count' : IDL.Nat, 'averageRating' : IDL.Float64 })],
      ['query'],
    ),
  'getIncident' : IDL.Func([IDL.Nat], [Incident], ['query']),
  'getMyDelayPredictions' : IDL.Func([], [IDL.Vec(DelayPrediction)], ['query']),
  'getMyJourneyHistory' : IDL.Func([], [IDL.Vec(Journey)], ['query']),
  'getMySOSReports' : IDL.Func([], [IDL.Vec(SOSReport)], ['query']),
  'getNetworkStatus' : IDL.Func([], [IDL.Opt(NetworkStatus)], ['query']),
  'getRecentIncidents' : IDL.Func([], [IDL.Vec(Incident)], ['query']),
  'getTPSIScore' : IDL.Func([IDL.Text], [IDL.Opt(TPSIScore)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeatherCache' : IDL.Func([], [IDL.Opt(WeatherData)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'resolveSOS' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCommuteAlert' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'saveJourney' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'storeDelayPrediction' : IDL.Func(
      [
        IDL.Record({
          'peakHour' : IDL.Bool,
          'temperature' : IDL.Float64,
          'dayOfWeek' : IDL.Nat,
          'line' : IDL.Text,
          'explanation' : IDL.Text,
          'predictedDelayMinutes' : IDL.Float64,
          'trainType' : IDL.Text,
          'distance' : IDL.Float64,
          'confidence' : IDL.Float64,
          'rainfall' : IDL.Float64,
          'timeOfDay' : IDL.Nat,
        }),
      ],
      [IDL.Nat],
      [],
    ),
  'submitFeedback' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'submitIncident' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'submitSOS' : IDL.Func([IDL.Text, IDL.Float64, IDL.Float64], [IDL.Nat], []),
  'updateNetworkStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateTPSIScore' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'updateWeatherCache' : IDL.Func([WeatherData], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Train = IDL.Record({
    'eta' : IDL.Text,
    'destination' : IDL.Text,
    'trainNumber' : IDL.Nat,
    'trainType' : IDL.Text,
    'platform' : IDL.Nat,
    'delay' : IDL.Float64,
  });
  const Analytics = IDL.Record({
    'totalSOSReports' : IDL.Nat,
    'averageDelayPrediction' : IDL.Float64,
    'averageRating' : IDL.Float64,
    'totalFeedback' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'openSOSReports' : IDL.Nat,
    'totalIncidents' : IDL.Nat,
    'resolvedSOSReports' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'username' : IDL.Text, 'email' : IDL.Text });
  const CommuteAlert = IDL.Record({
    'departureTime' : IDL.Text,
    'userId' : IDL.Principal,
    'daysOfWeek' : IDL.Vec(IDL.Nat),
    'sourceStation' : IDL.Text,
    'destinationStation' : IDL.Text,
  });
  const Incident = IDL.Record({
    'latitude' : IDL.Float64,
    'userId' : IDL.Principal,
    'description' : IDL.Text,
    'longitude' : IDL.Float64,
    'timestamp' : IDL.Int,
    'stationName' : IDL.Text,
    'incidentType' : IDL.Text,
  });
  const DelayPrediction = IDL.Record({
    'peakHour' : IDL.Bool,
    'temperature' : IDL.Float64,
    'userId' : IDL.Principal,
    'dayOfWeek' : IDL.Nat,
    'line' : IDL.Text,
    'explanation' : IDL.Text,
    'predictedDelayMinutes' : IDL.Float64,
    'trainType' : IDL.Text,
    'distance' : IDL.Float64,
    'timestamp' : IDL.Int,
    'confidence' : IDL.Float64,
    'rainfall' : IDL.Float64,
    'timeOfDay' : IDL.Nat,
  });
  const Journey = IDL.Record({
    'destination' : IDL.Text,
    'source' : IDL.Text,
    'userId' : IDL.Principal,
    'actualDelay' : IDL.Float64,
    'trainType' : IDL.Text,
    'timestamp' : IDL.Int,
    'predictedDelay' : IDL.Float64,
    'scheduledDeparture' : IDL.Text,
  });
  const SOSReport = IDL.Record({
    'latitude' : IDL.Float64,
    'resolved' : IDL.Bool,
    'userId' : IDL.Principal,
    'longitude' : IDL.Float64,
    'message' : IDL.Text,
    'response' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
  });
  const NetworkStatus = IDL.Record({
    'status' : IDL.Text,
    'timestamp' : IDL.Int,
    'reason' : IDL.Text,
  });
  const TPSIScore = IDL.Record({
    'trend' : IDL.Text,
    'line' : IDL.Text,
    'score' : IDL.Nat,
    'timestamp' : IDL.Int,
  });
  const WeatherData = IDL.Record({
    'temperature' : IDL.Float64,
    'humidity' : IDL.Float64,
    'timestamp' : IDL.Int,
    'rainfall' : IDL.Float64,
    'condition' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCommuteAlert' : IDL.Func([IDL.Nat], [], []),
    'deleteIncident' : IDL.Func([IDL.Nat], [], []),
    'deleteSOS' : IDL.Func([IDL.Nat], [], []),
    'getAllTrains' : IDL.Func([], [IDL.Vec(Train)], ['query']),
    'getAnalyticsSummary' : IDL.Func([], [Analytics], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommuteAlert' : IDL.Func([IDL.Nat], [CommuteAlert], ['query']),
    'getFeedbackStats' : IDL.Func(
        [],
        [IDL.Record({ 'count' : IDL.Nat, 'averageRating' : IDL.Float64 })],
        ['query'],
      ),
    'getIncident' : IDL.Func([IDL.Nat], [Incident], ['query']),
    'getMyDelayPredictions' : IDL.Func(
        [],
        [IDL.Vec(DelayPrediction)],
        ['query'],
      ),
    'getMyJourneyHistory' : IDL.Func([], [IDL.Vec(Journey)], ['query']),
    'getMySOSReports' : IDL.Func([], [IDL.Vec(SOSReport)], ['query']),
    'getNetworkStatus' : IDL.Func([], [IDL.Opt(NetworkStatus)], ['query']),
    'getRecentIncidents' : IDL.Func([], [IDL.Vec(Incident)], ['query']),
    'getTPSIScore' : IDL.Func([IDL.Text], [IDL.Opt(TPSIScore)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeatherCache' : IDL.Func([], [IDL.Opt(WeatherData)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'resolveSOS' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCommuteAlert' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'saveJourney' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'storeDelayPrediction' : IDL.Func(
        [
          IDL.Record({
            'peakHour' : IDL.Bool,
            'temperature' : IDL.Float64,
            'dayOfWeek' : IDL.Nat,
            'line' : IDL.Text,
            'explanation' : IDL.Text,
            'predictedDelayMinutes' : IDL.Float64,
            'trainType' : IDL.Text,
            'distance' : IDL.Float64,
            'confidence' : IDL.Float64,
            'rainfall' : IDL.Float64,
            'timeOfDay' : IDL.Nat,
          }),
        ],
        [IDL.Nat],
        [],
      ),
    'submitFeedback' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'submitIncident' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'submitSOS' : IDL.Func([IDL.Text, IDL.Float64, IDL.Float64], [IDL.Nat], []),
    'updateNetworkStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateTPSIScore' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'updateWeatherCache' : IDL.Func([WeatherData], [], []),
  });
};

export const init = ({ IDL }) => { return []; };