/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TPSIScore {
    trend: string;
    line: string;
    score: bigint;
    timestamp: bigint;
}
export interface NetworkStatus {
    status: string;
    timestamp: bigint;
    reason: string;
}
export interface Journey {
    destination: string;
    source: string;
    userId: Principal;
    actualDelay: number;
    trainType: string;
    timestamp: bigint;
    predictedDelay: number;
    scheduledDeparture: string;
}
export interface Analytics {
    totalSOSReports: bigint;
    averageDelayPrediction: number;
    averageRating: number;
    totalFeedback: bigint;
    totalUsers: bigint;
    openSOSReports: bigint;
    totalIncidents: bigint;
    resolvedSOSReports: bigint;
}
export interface Incident {
    latitude: number;
    userId: Principal;
    description: string;
    longitude: number;
    timestamp: bigint;
    stationName: string;
    incidentType: string;
}
export interface WeatherData {
    temperature: number;
    humidity: number;
    timestamp: bigint;
    rainfall: number;
    condition: string;
}
export interface SOSReport {
    latitude: number;
    resolved: boolean;
    userId: Principal;
    longitude: number;
    message: string;
    response?: string;
    timestamp: bigint;
}
export interface Train {
    eta: string;
    destination: string;
    trainNumber: bigint;
    trainType: string;
    platform: bigint;
    delay: number;
}
export interface DelayPrediction {
    peakHour: boolean;
    temperature: number;
    userId: Principal;
    dayOfWeek: bigint;
    line: string;
    explanation: string;
    predictedDelayMinutes: number;
    trainType: string;
    distance: number;
    timestamp: bigint;
    confidence: number;
    rainfall: number;
    timeOfDay: bigint;
}
export interface UserProfile {
    username: string;
    email: string;
}
export interface CommuteAlert {
    departureTime: string;
    userId: Principal;
    daysOfWeek: Array<bigint>;
    sourceStation: string;
    destinationStation: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteCommuteAlert(alertId: bigint): Promise<void>;
    deleteIncident(incidentId: bigint): Promise<void>;
    deleteSOS(reportId: bigint): Promise<void>;
    getAllTrains(): Promise<Array<Train>>;
    getAnalyticsSummary(): Promise<Analytics>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCommuteAlert(alertId: bigint): Promise<CommuteAlert>;
    getFeedbackStats(): Promise<{
        count: bigint;
        averageRating: number;
    }>;
    getIncident(incidentId: bigint): Promise<Incident>;
    getMyDelayPredictions(): Promise<Array<DelayPrediction>>;
    getMyJourneyHistory(): Promise<Array<Journey>>;
    getMySOSReports(): Promise<Array<SOSReport>>;
    getNetworkStatus(): Promise<NetworkStatus | null>;
    getRecentIncidents(): Promise<Array<Incident>>;
    getTPSIScore(line: string): Promise<TPSIScore | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWeatherCache(): Promise<WeatherData | null>;
    isCallerAdmin(): Promise<boolean>;
    resolveSOS(reportId: bigint, response: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveCommuteAlert(source: string, destination: string, departureTime: string, daysOfWeek: Array<bigint>): Promise<bigint>;
    saveJourney(source: string, destination: string, trainType: string, scheduledDeparture: string, predictedDelay: number, actualDelay: number): Promise<bigint>;
    storeDelayPrediction(input: {
        peakHour: boolean;
        temperature: number;
        dayOfWeek: bigint;
        line: string;
        explanation: string;
        predictedDelayMinutes: number;
        trainType: string;
        distance: number;
        confidence: number;
        rainfall: number;
        timeOfDay: bigint;
    }): Promise<bigint>;
    submitFeedback(rating: bigint, comment: string): Promise<bigint>;
    submitIncident(stationName: string, incidentType: string, description: string, latitude: number, longitude: number): Promise<bigint>;
    submitSOS(message: string, latitude: number, longitude: number): Promise<bigint>;
    updateNetworkStatus(status: string, reason: string): Promise<void>;
    updateTPSIScore(line: string, score: bigint, trend: string): Promise<void>;
    updateWeatherCache(data: WeatherData): Promise<void>;
}
import type { NetworkStatus as _NetworkStatus, SOSReport as _SOSReport, TPSIScore as _TPSIScore, UserProfile as _UserProfile, UserRole as _UserRole, WeatherData as _WeatherData } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteCommuteAlert(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCommuteAlert(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCommuteAlert(arg0);
            return result;
        }
    }
    async deleteIncident(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteIncident(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteIncident(arg0);
            return result;
        }
    }
    async deleteSOS(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSOS(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSOS(arg0);
            return result;
        }
    }
    async getAllTrains(): Promise<Array<Train>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTrains();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTrains();
            return result;
        }
    }
    async getAnalyticsSummary(): Promise<Analytics> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalyticsSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalyticsSummary();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCommuteAlert(arg0: bigint): Promise<CommuteAlert> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommuteAlert(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommuteAlert(arg0);
            return result;
        }
    }
    async getFeedbackStats(): Promise<{
        count: bigint;
        averageRating: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedbackStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedbackStats();
            return result;
        }
    }
    async getIncident(arg0: bigint): Promise<Incident> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncident(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncident(arg0);
            return result;
        }
    }
    async getMyDelayPredictions(): Promise<Array<DelayPrediction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyDelayPredictions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyDelayPredictions();
            return result;
        }
    }
    async getMyJourneyHistory(): Promise<Array<Journey>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyJourneyHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyJourneyHistory();
            return result;
        }
    }
    async getMySOSReports(): Promise<Array<SOSReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySOSReports();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySOSReports();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNetworkStatus(): Promise<NetworkStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNetworkStatus();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNetworkStatus();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecentIncidents(): Promise<Array<Incident>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentIncidents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentIncidents();
            return result;
        }
    }
    async getTPSIScore(arg0: string): Promise<TPSIScore | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTPSIScore(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTPSIScore(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeatherCache(): Promise<WeatherData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeatherCache();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeatherCache();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async resolveSOS(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveSOS(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveSOS(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveCommuteAlert(arg0: string, arg1: string, arg2: string, arg3: Array<bigint>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCommuteAlert(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCommuteAlert(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async saveJourney(arg0: string, arg1: string, arg2: string, arg3: string, arg4: number, arg5: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveJourney(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveJourney(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async storeDelayPrediction(arg0: {
        peakHour: boolean;
        temperature: number;
        dayOfWeek: bigint;
        line: string;
        explanation: string;
        predictedDelayMinutes: number;
        trainType: string;
        distance: number;
        confidence: number;
        rainfall: number;
        timeOfDay: bigint;
    }): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.storeDelayPrediction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeDelayPrediction(arg0);
            return result;
        }
    }
    async submitFeedback(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitFeedback(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitFeedback(arg0, arg1);
            return result;
        }
    }
    async submitIncident(arg0: string, arg1: string, arg2: string, arg3: number, arg4: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitIncident(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitIncident(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async submitSOS(arg0: string, arg1: number, arg2: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitSOS(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitSOS(arg0, arg1, arg2);
            return result;
        }
    }
    async updateNetworkStatus(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNetworkStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNetworkStatus(arg0, arg1);
            return result;
        }
    }
    async updateTPSIScore(arg0: string, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTPSIScore(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTPSIScore(arg0, arg1, arg2);
            return result;
        }
    }
    async updateWeatherCache(arg0: WeatherData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWeatherCache(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWeatherCache(arg0);
            return result;
        }
    }
}
function from_candid_SOSReport_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SOSReport): SOSReport {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NetworkStatus]): NetworkStatus | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TPSIScore]): TPSIScore | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WeatherData]): WeatherData | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    latitude: number;
    resolved: boolean;
    userId: Principal;
    longitude: number;
    message: string;
    response: [] | [string];
    timestamp: bigint;
}): {
    latitude: number;
    resolved: boolean;
    userId: Principal;
    longitude: number;
    message: string;
    response?: string;
    timestamp: bigint;
} {
    return {
        latitude: value.latitude,
        resolved: value.resolved,
        userId: value.userId,
        longitude: value.longitude,
        message: value.message,
        response: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.response)),
        timestamp: value.timestamp
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SOSReport>): Array<SOSReport> {
    return value.map((x)=>from_candid_SOSReport_n7(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
